### ISSUE TITLE
Uncaught TypeError: this.goconfig is not a function

### ISSUE THREAD

**Issue by melihmucuk** [joefitzgerald/gofmt#4]
[Enter steps to reproduce below:]
1. open atom
2. add project folder
3. select $GOPATH folder

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [gofmt](https://github.com/joefitzgerald/gofmt) package, v1.0.3
### Stack Trace

Uncaught TypeError: this.goconfig is not a function

```
At /Users/melihmucuk/.atom/packages/gofmt/lib/formatter.js:109

TypeError: this.goconfig is not a function
    at Formatter.updateFormatterCache (/Users/melihmucuk/.atom/packages/gofmt/lib/formatter.js:109:23)
    at /Users/melihmucuk/.atom/packages/gofmt/lib/formatter.js:46:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:255:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:869:41
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:30:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -0:42.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-monokai-seti.theme-one-dark-ui)
     -0:12.2.0 golang:godef (ul.list-inline.tab-bar.inset-panel)
     -0:05.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-go, v1.0.4
environment, v1.1.1
file-icons, v1.6.18
go-config, v1.1.2
go-get, v1.0.1
go-plus, v4.0.1
gofmt, v1.0.3
gometalinter-linter, v1.0.3
gorename, v1.0.0
linter, v1.11.3
monokai-seti, v0.7.0
navigator-godef, v1.0.2
pigments, v0.24.5
react, v0.14.1
terminal-plus, v0.14.5
tester-go, v1.0.1

# Dev
No dev packages
```

**Comment by cristian-sima** [comment]
+1
update: solved

**Comment by joefitzgerald** [comment]
As a side note you should ensure the go-config package is installed and enabled, or nothing else go-plus related will work.
