### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by mbrevoort** [joefitzgerald/gofmt#7]
[Enter steps to reproduce below:]
1. With go file in buffer, Package -> Go -> Format With goimports

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [gofmt](https://github.com/joefitzgerald/gofmt) package, v1.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/mike/.atom/packages/gofmt/lib/formatter.js:276

TypeError: Cannot read property 'getPath' of undefined
    at Formatter.format (/Users/mike/.atom/packages/gofmt/lib/formatter.js:276:24)
    at atom-workspace.<anonymous> (/Users/mike/.atom/packages/gofmt/lib/formatter.js:57:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -5:54 core:backspace (atom-text-editor.editor.is-focused)
     -5:53.1.0 core:save (atom-text-editor.editor.is-focused)
     -5:49.8.0 core:undo (atom-text-editor.editor.is-focused)
     -5:48.8.0 core:save (atom-text-editor.editor.is-focused)
     -4:48.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -4:43.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:43.9.0 golang:gofmt (atom-text-editor.editor)
     -3:25.1.0 core:save (atom-text-editor.editor.is-focused)
     -3:21.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -3:21.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:21.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -3:19.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:19.5.0 core:save (atom-text-editor.editor.is-focused)
     -3:09.3.0 core:undo (atom-text-editor.editor.is-focused)
     -3:08.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.0 golang:goimports (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "gofmt": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-go, v1.0.4
environment, v1.2.0
go-config, v1.1.2
go-get, v1.0.1
go-plus, v4.0.1
gofmt, v1.1.2
gometalinter-linter, v1.0.4
gorename, v1.0.0
linter, v1.11.4
navigator-godef, v1.0.2
tester-go, v1.0.2

# Dev
No dev packages
```

**Comment by joelsimonoff** [comment]
I am experiencing the exact same issue. It started when I updated to go plus 4.0.1 and atom 1.6.0.

**Comment by mbrevoort** [comment]
Looks like it was probably introduced with this commit. https://github.com/joefitzgerald/gofmt/commit/3000e6ffe638371b3317e7b5cb975fcc6a67754c

`buffer` isn't defined yet

**Comment by joefitzgerald** [comment]
Sorry about this folks. Please update to `v1.1.3`.

**Comment by mbrevoort** [comment]
Thanks Joe
